# Required to connect to your outgoing mail server. Example for using gmail:
# gmail
SMTP_SERVER: smtp.gmail.com
#SMTP_PORT: 587
SMTP_PORT: 25
USERNAME: myemail@gmail.com
PASSWORD: "pass"

TIMEZONE: 'US/Pacific'

PARTICIPANTS:
---
  - name: Zach 0
  - handle: test0
  - email: test0@gmail.com
  - address: 11111 beach ave San Diego, CA  92126 United States
---
  - name: Zach 1
  - handle: test1
  - email: test1@gmail.com
  - address: 29403 buffalo, st Iowa, 52241
---
  - name: Zach 2
  - handle: test2
  - email: test2@gmail.com
  - address: 102324 test rd, CA  92126 United States
# Warning -- if you mess this up you could get an infinite loop
DONT-PAIR:
  - Chad, Jen    # Chad and Jen are married
##  - Chad, Bill   # Chad and Bill are best friends
##  - Bill, Sharon

# From address should be the organizer in case participants have any questions
FROM: You <myemail@gmail.com>

# Both SUBJECT and MESSAGE can include variable substitution for the 
# "santa" and "santee"
SUBJECT: Your secret santa recipient is {santee}
MESSAGE: 
  Dear {santa},
  
  This year you are {santee}'s Secret Santa!. Ho Ho Ho!
  
  The maximum spending limit is 50.00
  
  
  This message was automagically generated from a computer. 
  
  Nothing could possibly go wrong...
  
  http://github.com/underbluewaters/secret-santa
  
